server:
  port: 9090
  
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: 1234
    url: jdbc:mariadb://localhost:3306/starcafe
    username: starcafe
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  config-location: classpath:mybatis-config.xml

logging:
  level:
    '[org.springframework.boot.sql]': trace
    '[org.mybatis.spring]': trace
    '[org.mariadb.jdbc.client.impl.StandardClient]': trace