server:
  port: 9090

  
spring:
 mvc:
  view:
   prefix: /WEB-INF/view/
   suffix: .jsp
   
 datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: madang
    password: madang
    
mybatis:
 config-location: classpath:mybatis-config.xml
 
 